Fix a bug with node deletion
dgreene1/react-accessible-treeview pull request #132
Opened 2023-06-28 14:41 UTC by mihna123

### What does this PR do?
It fixes a bug with node deletion. The bug happens when you send data with some nodes missing (because you deleted them) to _TreeView_ component, and you want to have all nodes expanded with _expandedId_ prop. This small fix just checks if node is still in the tree before trying to collapse it, otherwise the exception "Node with id=x doesn't exist in the tree" will be thrown.

2023-06-28 18:25 UTC, dgreene1 commented
@mihna123 we need to have an issue that explains the defect before we get a PR.

Also, we can’t merge code that doesn’t have a unit test. If there is a bug, we’ll need to make sure that the unit test fails when your code is missing and passes once your fix is present.

2023-06-29 07:16 UTC, mihna123 commented
> @mihna123 we need to have an issue that explains the defect before we get a PR.
> 
> Also, we can’t merge code that doesn’t have a unit test. If there is a bug, we’ll need to make sure that the unit test fails when your code is missing and passes once your fix is present.

Sorry, i will make an issue then

2023-06-29 08:42 UTC, mihna123 commented
@dgreene1 here is the issue #133

2023-08-14 07:14 UTC, callwait commented
I faced this issue as well, can you merge it?

2023-08-14 11:30 UTC, dgreene1 commented
@mihna123 this PR lacks unit tests. In order for us to know that the bug is fixed, we need a unit test. This will also ensure that it does not regress in the future, as long as the test fails when your fix is removed and passes when your fix is present.

cc @callwait

2023-08-14 11:32 UTC, dgreene1 requested changes
unit tests are required. Within this tests, please make sure that you don’t call setData inside of a recursive function like I mention in https://github.com/dgreene1/react-accessible-treeview/issues/133#issuecomment-1620550713

2023-10-20 19:23 UTC, closed without merging